### ISSUE TITLE
Not Working in Ubuntu

### ISSUE THREAD

**Issue by denzelwamburu** [Aluxian/WhatsApp-Desktop#66] opened 2015-10-10 16:11 UTC
Nice stuff but after i downloaded, it worked but trying to use it for the second time itd giving recommendations of browser clients. Can't seem to work after that. 
![screenshot from 2015-10-10 18 57 57](https://cloud.githubusercontent.com/assets/6532631/10412057/8ebe2c94-6f82-11e5-84b0-131196afa54b.png)

**Comment by peterrus** [comment] 2015-10-10 16:25
experiencing the same

**Comment by peterrus** [comment] 2015-10-10 16:27
duplicate of #60

**Comment by denzelwamburu** [comment] 2015-10-11 10:38
Great, sorry didn't see that, but its not really cool that after deleting
the Application Cache still regenerates it.

**Closed** 2015-10-11 10:38 UTC
