### ISSUE TITLE
App doesn't run

### ISSUE THREAD

**Issue by ozgrozer** [Aluxian/WhatsApp-Desktop#49] opened 2015-08-25 11:22 UTC
Hi,

WhatsApp Desktop doesn't run.

Here's a screenshot.

![screenshot 2015-08-25 14 19 11](https://cloud.githubusercontent.com/assets/651938/9465324/66c7d216-4b34-11e5-8641-1889a77a8cd0.png)

**Comment by RoBi89** [comment] 2015-08-25 13:46
Same

**Comment by Swisyn** [comment] 2015-08-25 13:56
Same

**Comment by carlos-stored** [comment] 2015-08-26 13:07
Same problem

**Comment by quassy** [comment] 2015-08-26 13:39
This is a duplicate of #42. No need to report the same bug over and over again.

**Comment by reand** [comment] 2016-03-22 04:21
My name is Nandy.

It is nice and joyful to see your profile on https://github.com and i thought is beautiful to make you a friend,looking for a good friendship, mail me to my box, because i am not often here on https://github.com (nandy1121@hotmail.com ) for more introduction and i will send you my picture.

Nandy

**Comment by mpazisilupumbwe** [comment] 2016-03-22 07:55
Mine is Justin.

Nice of you to send me an email Nandy. Of course we can be friends. I will
wait for that photo

Justin

**Comment by Aluxian** [comment] 2016-04-02 12:38
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

I've fixed this problem in Whatsie by changing the user agent.

**Closed by Aluxian** 2016-04-02 12:38 UTC
