### ISSUE TITLE
After launch it ask me to install one of the other browsers.

### ISSUE THREAD

**Issue by bboerendans** [Aluxian/WhatsApp-Desktop#48] opened 2015-08-21 09:24 UTC
I'm using Windows 10. Reinstall did not solve this issue. It was working some days ago, after a force close I'm getting this message.

![knipsel](https://cloud.githubusercontent.com/assets/4182238/9405318/1bddee42-47f7-11e5-848c-bd11e9685c5b.PNG)

**Comment by MarioVillani** [comment] 2015-08-21 09:50
Same problem here...

**Comment by bilby91** [comment] 2015-08-21 15:11
Same here :(

**Comment by sgade** [comment] 2015-08-21 20:11
First boot behaved as expected, now after restart I'm getting the same dialog.

**Comment by B00StER** [comment] 2015-08-22 07:48
Disabling the cache worked for me too.

**Comment by Helmi** [comment] 2015-08-22 09:55
Is there any way to disable the cache permanently not only with the dev tools open?

**Comment by azat-io** [comment] 2015-08-22 18:52
Are there ways to solve this problem?
It's very bad.

**Comment by marcferna** [comment] 2015-08-22 20:03
Maybe one option is to change the User-Agent to trick WhatsApp web to think that is a Chrome browser?

**Comment by kdekooter** [comment] 2015-08-24 06:55
Is WhatsApp actively sabotaging this kind of apps now?

**Comment by Helmi** [comment] 2015-08-24 08:05
Just read above guys - it's not a UA-issue but a cache problem.

**Comment by quassy** [comment] 2015-08-26 13:40
This is a duplicate of #42. No need to report the same bug over and over again.

**Comment by wiesson** [comment] 2015-09-02 06:42
@sgade, thanks for this workaround!

**Comment by tmjunk** [comment] 2015-09-09 05:19
worked just fine
maybe you should add a button to disable cache?
most users don't know hot to do it.

**Comment by Aluxian** [comment] 2016-04-02 12:39
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

I've fixed this problem in Whatsie by changing the user agent.

**Closed by Aluxian** 2016-04-02 12:39 UTC
