### ISSUE TITLE
Chromium

### ISSUE THREAD

**Issue by sadalavoaoj** [Aluxian/WhatsApp-Desktop#62] opened 2015-09-17 21:46 UTC
Hi there,

I cannot run anymore whatsapp on cinnamon 17.2. It asks for chrome (i use chromium) and dont pass from the intro.

The name on the window bar is always shaking. What am i doing wrong?

Best regards,

**Comment by WoodyWoodsta** [comment] 2015-09-25 07:03
I was having this issue as well. Works correctly on first run, however displays the "use one of these browsers" windows any other time I try to run it.

**Comment by starquake** [comment] 2015-10-02 06:36
Duplicate of #42

**Comment by sadalavoaoj** [comment] 2015-10-12 21:51
Thanks, i just deleted index file inside Application Cache and then removed permissions to my user "Application Cache" folder too.

Now it is working, it is a work around but it works.

**Closed** 2015-10-12 21:55 UTC

**Comment by WoodyWoodsta** [comment] 2015-10-20 08:41
How is this issue closed due to a workaround?

**Comment by sadalavoaoj** [comment] 2015-10-21 22:38
I closed because it was duplicated, see #42, it is the same issue and same work arounds.

Cheers.
