### ISSUE TITLE
Pressing ESC button close the application

### ISSUE THREAD

**Issue by streambinder** [Aluxian/WhatsApp-Desktop#30] opened 2015-06-25 13:45 UTC
Don't know if it's an expected behavior, but don't think it's useful anyway.

**Comment by Aluxian** [comment] 2015-06-25 13:47
Somebody requested it before, and it was a minor thing to add. What platform are you on? I'm thinking I should probably only enable it for Windows.

**Comment by streambinder** [comment] 2015-06-25 13:48
Linux Fedora 22.

**Comment by Ishmaeel** [comment] 2015-07-02 15:20
I too think this feature does not make much sense - even on Windows. I'm trained to dismiss image/media popups with ESC key and having it close the whole window is kinda jarring.

Make it optional perhaps?

**Comment by MartijnDevNull** [comment] 2015-07-08 14:38
Would like to see this to, highly annoying

**Comment by MartijnDevNull** [comment] 2015-07-08 14:40
I'm on Debian btw, I don't think this should be a platform specific option

**Comment by hashworks** [comment] 2015-11-23 16:46
Yeah +1, this annoys me as well. I'm always pressing ESC when I want to close a picture popup.

**Comment by rodgerpaulo** [comment] 2015-11-24 11:58
+1 every time i'm hit ESC expecting to close

**Comment by vukasin0** [comment] 2015-12-06 16:22
Hate this too - plz remove it. ESC should only closing popups inside app but not APP.

**Comment by gtataranni** [comment] 2016-01-21 13:55
+1 I'm on Mint and also affects me. Every time I want to close a picture preview and I press ESC I close the application instead

**Comment by Aluxian** [comment] 2016-04-02 12:45
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Closed by Aluxian** 2016-04-02 12:45 UTC
