### ISSUE TITLE
Cant load..

### ISSUE THREAD

**Issue by bijtje** [Aluxian/WhatsApp-Desktop#87] opened 2016-02-06 21:35 UTC
When starting it shows this screen: http://prntscr.com/9zwwyx cant load the content...

**Comment by Airon90** [comment] 2016-02-07 11:58
Duplicate of #42, #48 and #55
Please, check closed issues before opening a new one ;)

**Comment by bijtje** [comment] 2016-02-07 13:43
I'm sorry

**Closed** 2016-02-07 13:43 UTC
