### ISSUE TITLE
Problem when launching the program

### ISSUE THREAD

**Issue by Dimbadboy** [Aluxian/WhatsApp-Desktop#74] opened 2015-10-27 15:28 UTC
Hello, first time when I launched the program it was running correctly, after that when I launch it it is giving me: 
"WhatsApp Web
Send and receive WhatsApp messages right from your computer.
We recommend using WhatsApp Web with one of the following browsers:
Google Chrome
Mozilla Firefox
Opera
WhatsApp Web also supports:
Safari (MacOS 10.8+ Only)"

Can someone help me? Thanks in advance.

**Comment by leolamanna** [comment] 2015-10-27 15:33
Same problem here... no solution founded  =(

**Comment by qcris** [comment] 2015-10-27 15:41
Try to delete the "Application Cache" and "Cache" folders and it works: https://github.com/Aluxian/WhatsApp-Desktop/issues/42

**Comment by leolamanna** [comment] 2015-10-27 15:51
it doesn´t work for me... deleting C:\Users\Your Name\AppData\Local\UnofficialWhatsApp\Application Cache\Cache\*.* has no effect
Anyway (if it would have worked), I'm wondering if I will be forced to do a process like that, averytime I run the app (!?)
I loved this app, for the few ours It worked...

**Comment by Dimbadboy** [comment] 2015-10-27 16:16
It is working but every time you need to restart the cache and scan the image again and again.

**Comment by leolamanna** [comment] 2015-10-27 16:29
yeap, I do a mistake and delete the content of "Cahe" folder... instead of "Application Cache".
I've done it in the right way... and works!!
but (there's always a "but") this method requires you do it EVERYTIME you run the app, wich is not so useful... or convenient.
So, I tried as suggested at [#42] (https://github.com/Aluxian/WhatsApp-Desktop/issues/42), to remove my own write permissions for that folder and it works!!
No need to manually delete any files... and no need to rescan de QR at startup!
(at least, by now!)

**Comment by Dimbadboy** [comment] 2015-10-27 17:11
Can you tell me what operation system are you using ? Thanks in advance.

**Comment by leolamanna** [comment] 2015-10-27 17:32
@Dimbadboy I'm using Windows 7... and the path to the folder is:
C:\Users\**Your Name**\AppData\Local\UnofficialWhatsApp\Application Cache\Cache

**Comment by zweicoder** [comment] 2015-10-31 09:48
There were some PRs submitted but this repo doesn't seem to be worked on anymore. Try my [fork](https://github.com/zweicoder/WhatsApp-Desktop) if you're interested. It deletes the cache every time you quit the application. Tell me if it doesn't work or raise an issue :)

**Comment by doylefermi** [comment] 2015-11-06 15:49
![screenshot from 2015-11-06 21 17 06](https://cloud.githubusercontent.com/assets/8755940/11001166/e6394c8e-84cb-11e5-91c0-0763523934f9.png)
Same issue found in Linux. However clearing the ApplicationCache fixes it. But tedious to delete cache everytime. Hope u find a fix soon.

OS: Ubuntu 14.04 LTS x64

**Comment by LucaScorpion** [comment] 2015-11-09 18:00
Same here, for some reason it didn't to this the first couple of times. Maybe WhatsApp found out and added something that breaks this program?

**Comment by brunofpmiranda** [comment] 2015-11-15 13:40
Does anyone knows where`s the cache dir on max os 10.11.1 El Captain?

Thanks.

**Comment by FWFabio** [comment] 2015-11-17 17:54
it's here: "~/Library/Application Support/UnofficialWhatsApp/Application Cache"

**Comment by henriquepagoto** [comment] 2015-11-19 00:36
Here erasing the index from the "Application Cache" worked

**Comment by AdrianoCahete** [comment] 2015-11-22 18:15
Click with right mouse button on that page, go to "Lauche Dev Tools", click in the top-right cog (Settings), mark "Disable Cache", click in the close button on top-right "x" (is somehow bugged, the click trigger is in the top, not the middle).

With "Dev Tools" windows opened, right-click in the main program again and choose "Reload" from dropdown menu.

**Comment by MrOutis** [comment] 2015-12-03 23:12
:+1: https://github.com/Aluxian/WhatsApp-Desktop/issues/74#issuecomment-154445299
Worked for me, thanks, @doylefermi !

**Comment by B12f13** [comment] 2015-12-04 14:07
Hello,
here for the Terminal...
 
rm -rf ~/.config/UnofficialWhatsApp

than it works.


The problem is annoying, you can not automate the command? 
Client is closed by user & automatically deleted the cache?

Thx

**Comment by selwynorren** [comment] 2015-12-04 14:08
Hi why not simply render the folder unwritable, this works for me on a permanent basis. App runs flawlessly this way

**Comment by doylefermi** [comment] 2015-12-04 14:09
yes do that. thats y we removed all permissions. 

sudo chmod 000 "Application Cache"

**Comment by shoguevara** [comment] 2015-12-09 17:23
Deleting folder cache is not a fix! It's just a lame workaround. After deleting cache you have to scan QR again and again. It's much easier to use a pinned tab in browser. Or create separate browser app (both chrome and firefox has such capabilities). Why someone would need the app then?
Can it be true, that there is no way to override UserAgent detection?
Don't get me wrong, I really appreciate what the developers done, especially considering that this soft is free.. But you don't have to make a workaround look like a bugfix. Sorry if I did hurt someones feelings.

**Comment by AdrianoCahete** [comment] 2015-12-09 18:04
> After deleting cache you have to scan QR again and again.

Not if you use DevTools workaround.

**Comment by mauricio-sousa** [comment] 2015-12-09 19:42
remove only the file "$HOME/.config/UnofficialWhatsApp/Application\ Cache/Cache/index" worked for me before each startup.

**Comment by AdrianoCahete** [comment] 2015-12-09 20:43
I tried to fix this bug (is just add ```nwuseragent``` parameter with a valid UserAgent value (i tested with ```"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0"``` in ```src\app.html``` and build.
Build run fine, but i can't run executable before that. I'm a Windows 10 x64 OS, if anyone can build and try this fix for another plataform, it would be good.

For now i'm migrating to [bcalik/Whatsapp-Desktop](https://github.com/bcalik/Whatsapp-Desktop)

**Comment by e-M-c-E** [comment] 2015-12-21 15:05
Confirmed. The issue is also on Mint 17.3 Mate x64.
And the "workaround" by @doylefermi, works great! :)

**Comment by geraldoramos** [comment] 2016-01-20 01:08
@AdrianoCahete DevTools workaround worked great. I tried to change user agent in the app.html and also in the package.json. Tried both but after building the application, it runs fine but user agent doesn't change (Mac O.S)

**Comment by AdrianoCahete** [comment] 2016-01-20 16:56
@geraldoramos I forked the application, but didn't have time to research the problem. I hope i can have time in the next month.

**Comment by machimocho** [comment] 2016-02-05 15:55
@doylefermi that fix worked for me.. thanks

**Comment by beppe9000** [comment] 2016-02-19 13:31
lulz

**Comment by mrmayfield** [comment] 2016-03-02 06:08
`$ rm ~/Library/Application Support/UnofficialWhatsApp/Application Cache/Index`

Worked for me, thanks for some of the above answers. PS: I didn't have to rescan my QR code.

**Comment by GexxOn** [comment] 2016-03-08 08:39
quickfix with a .bat file for windows
create a .bat file and insert this code
```
taskkill /f /im UnofficialWhatsApp.exe
@RD /S /Q "C:\Users\#Your-Username#\AppData\Local\UnofficialWhatsApp\Application Cache"
start "" "C:\Program Files (x86)\Unofficial WhatsApp for Desktop\UnofficialWhatsApp.exe" -screen 0 -clipboard -multiwindow`
````

**Comment by Aluxian** [comment] 2016-04-02 12:28
Hey, all, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Closed by Aluxian** 2016-04-02 12:28 UTC
