### ISSUE TITLE
App not being recognized as a supported browser by whatsapp servers

### ISSUE THREAD

**Issue by regisbsb** [Aluxian/WhatsApp-Desktop#89] opened 2016-02-11 10:41 UTC
![image](https://cloud.githubusercontent.com/assets/886819/12974440/e314c30e-d0ab-11e5-8c11-f5912fe5127b.png)

**Comment by regisbsb** [comment] 2016-02-11 10:41
@Aluxian may I help in any shape or form?

**Comment by nibbl3r** [comment] 2016-02-11 17:20
@Aluxian I'm having the same "issue" as regisbsb. 
In fact its probably not an issue, but some misunderstanding from our part. 
When we start the desktop app it goes direct to the page @regisbsb posted (inside the apps frame). 

I've selected the chrome browser, but it just goes to here:
![image](https://cloud.githubusercontent.com/assets/17181941/12983869/2a60fb10-d0e3-11e5-9b80-7fc1b0c862ec.png)

I suppose we should just add the app from the chrome store, but in the chrome store there's nothing from @Aluxian.

I would guess that it's 1 of 3:
1 - missing app from chrome store
2 - incorrect link @app start
3 - dummies between chair and keyb

Thanks for your help!

**Comment by nibbl3r** [comment] 2016-02-11 17:30
Ignore previous.
Already reported in #74.

Please close

**Comment by beppe9000** [comment] 2016-02-19 13:31
lulz

**Comment by beppe9000** [comment] 2016-02-19 13:33
i'm not saying this is bad, but... why is this advertised as  a "desktop client"... if it uses whatsapp web? desktop client = standalone client

**Comment by mrmayfield** [comment] 2016-03-02 05:26
It's a desktop client but it's basically an iframe to the web app, it's built on top of it from what I can tell. But I'm receiving the same error as reported above, it was working perfectly before I want it back!!

**Comment by beppe9000** [comment] 2016-03-02 12:19
Having to have a connected mobile with the app totally defies the meaning of a desktop client. A desktop client is useless i i need to keep my phoone connected: it's extremely dumb.

**Comment by regisbsb** [comment] 2016-03-02 14:10
Guys, stop being dicks, this a fucking opensouce project. Fork it and pull
request or submit a bug report and wait. Otherwise fuck off, stop talking
about dummies and stupidity when you are the stupid dummies.

**Comment by mrmayfield** [comment] 2016-03-02 17:44
Relax man, this is what I posted in the other issue (this one should be closed as duplicate).

`$ rm ~/Library/Application Support/UnofficialWhatsApp/Application Cache/Index
`
Worked for me, thanks for some of the above answers. PS: I didn't have to rescan my QR code.

Won't have a chance to poke around in source code until tomorrow, but maybe we can add a hook on application close to remove the cache?

**Comment by beppe9000** [comment] 2016-03-02 18:24
What about overwriting the User Agent?

**Comment by Aluxian** [comment] 2016-03-02 18:27
THIS! This is the right solution. This is what I did for Whatsie (WhatsApp for Desktop v2), on which I’m still working.
On 2 March 2016 at 20:24:45, beppe9000 (notifications@github.com) wrote:

What about overwriting the User Agent?

**Comment by mrmayfield** [comment] 2016-03-02 21:18
Yeah overwriting the User Agent seems like the logical process. And it looks like this port is even buggy, I discovered today audio recordings don't playback properly when sent by others. But it seems like it's more Whatsapp stepping on the little guys as opposed to issues with the OS community. 

I don't care if it's just a desktop way to access the web app, because the web app seems to work properly, if we can get the desktop version to do the same that's fine with me.

**Comment by bloqhead** [comment] 2016-03-16 13:56
I run into the same thing every time. Couldn't find a fix so I fell back to [WhatsChrome.](https://chrome.google.com/webstore/detail/whatschrome/bgkodfmeijboinjdegggmkbkjfiagaan?hl=en)

**Comment by regisbsb** [comment] 2016-03-16 22:15
@bloqhead dick party this issue. stop bitching start a Pull Request

**Comment by mrmayfield** [comment] 2016-03-16 23:52
Lol to be honest @regisbsb , I'm glad @bloqhead mentioned that app, I'm using that and it's working perfectly for me

**Comment by regisbsb** [comment] 2016-03-16 23:56
well it's not a desktop app, it's a chrome app, no auto startup with the browser, better off with a pinned tab...

**Comment by regisbsb** [comment] 2016-03-16 23:57
i'm still using the app, just open the chrome tools and disable cache and reload the app...

**Comment by bloqhead** [comment] 2016-03-25 14:22
Despite being a dick, your solution works for me, @regisbsb

**Comment by regisbsb** [comment] 2016-03-25 16:01
You are welcome @bloqhead. At least I'm a useful dick not a flaccid one as everybody here...

**Comment by Aluxian** [comment] 2016-04-02 12:20
Hey, everyone, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Closed by Aluxian** 2016-04-02 12:20 UTC
