### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by isc30** [Aluxian/WhatsApp-Desktop#55] opened 2015-09-03 17:49 UTC
Whatsapp webpage updated 5 minutes ago, disabling support for Edge useragent, maybe spoofing user agent to chrome will solve the bug. There is also another bug: audios wont load
(Windows 10 professional 64 bits)

![](https://i.gyazo.com/42c9cff362656347224105325be15d12.png)

**Comment by starquake** [comment] 2015-09-04 16:37
Same issue here with Mac OS X 10.10.4

**Comment by starquake** [comment] 2015-09-04 16:41
This is a duplicate of this: https://github.com/Aluxian/WhatsApp-Desktop/issues/48

**Comment by phoenix-frozen** [comment] 2015-09-10 14:09
... which is, in turn, a duplicate of #42

**Comment by Aluxian** [comment] 2016-04-02 12:37
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

I fixed this problem there.

**Closed by Aluxian** 2016-04-02 12:37 UTC
